server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.87.101:8848
    alicloud:
      access-key: LTAI5tAyUdDxcCYZvSj8iVzh
      secret-key: MlcubNQqBXWxdAloToEIeyab9Hgexa
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        #默认没有这个属性，我们自己写的
        bucket: gulimall-zhuangjie-resource
  notify:
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      sign: 30fa725601884ec1875338dd6719b5ed
      skin: 9d7d67e3ce42423dbc1e570813dc0f8a
      appcode: 410bce9766324e1ca9c0a72f3a4fffd6
    email:
      host: smtp.qq.com
      auth-key: ehfgrgyrsdmecdhc
      from: 2119299531@qq.com




