server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.87.101:8848
    alicloud:
      access-key: LTAI5tAyUdDxcCYZvSj8iVzh
      secret-key: MlcubNQqBXWxdAloToEIeyab9Hgexa
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        #默认没有这个属性，我们自己写的
        bucket: gulimall-zhuangjie-resource




